// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function id(x) {
  return x;
}

function map_pair(r, param) {
  return [
          Curry._1(r.f, param[0]),
          Curry._1(r.f, param[1])
        ];
}

map_pair({
      f: id
    }, [
      3,
      true
    ]);

function map_pair$1(f1, f2, param) {
  return [
          Curry._1(f1, param[0]),
          Curry._1(f2, param[1])
        ];
}

map_pair$1(id, id, [
      1,
      true
    ]);

function map_pair$2(f, param) {
  return [
          Curry._1(f, param[0]),
          Curry._1(f, param[1])
        ];
}

var sample = map_pair$2(id, [
      1,
      true
    ]);

exports.id = id;
exports.map_pair = map_pair$2;
exports.sample = sample;
/*  Not a pure module */
