// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function id(x) {
  return x;
}

function map_pair(f, param) {
  return [
          Curry._1(f, param[0]),
          Curry._1(f, param[1])
        ];
}

var sample = map_pair(id, [
      1,
      true
    ]);

console.log(sample);

exports.id = id;
exports.map_pair = map_pair;
exports.sample = sample;
/* sample Not a pure module */
